# try with finally
# try with else
try:
    i = int(input("enter a number:\n"))
    c = 1/i
except Exception as e:
    print(e)
    exit()
finally:
    print("we were successful")
    

















































